name:                 CW3
version:              0.1.0.0
visibility:           public
id:                   CW3-0.1.0.0-inplace
key:                  CW3-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           alongbijalawal2000@gmail.com
author:               lawal
abi:                  inplace
exposed:              True
exposed-modules:
    MyLib SubstringSearch SuffixTree SuffixTree2 SuffixTree3
    SuffixTree4 SuffixTree5

import-dirs:
    /home/lawal/Code_linux/Haskell/AAD-Project/CW3/dist-newstyle/build/x86_64-linux/ghc-9.6.7/CW3-0.1.0.0/build

library-dirs:
    /home/lawal/Code_linux/Haskell/AAD-Project/CW3/dist-newstyle/build/x86_64-linux/ghc-9.6.7/CW3-0.1.0.0/build

library-dirs-static:
    /home/lawal/Code_linux/Haskell/AAD-Project/CW3/dist-newstyle/build/x86_64-linux/ghc-9.6.7/CW3-0.1.0.0/build

dynamic-library-dirs:
    /home/lawal/Code_linux/Haskell/AAD-Project/CW3/dist-newstyle/build/x86_64-linux/ghc-9.6.7/CW3-0.1.0.0/build

data-dir:             /home/lawal/Code_linux/Haskell/AAD-Project/CW3/.
hs-libraries:         HSCW3-0.1.0.0-inplace
depends:
    base-4.18.3.0 bytestring-0.11.5.4 containers-0.6.7
    hashtables-1.4.2-50cab17d04a64d97e6f711492c152a78db48c2720b9c501445240426361b8fac
    mtl-2.3.1
    vector-0.13.2.0-44a212992f25233ccd712d356a555b0bdaf449d50bb377a3a6ccef858aa7148f

haddock-interfaces:
    /home/lawal/Code_linux/Haskell/AAD-Project/CW3/dist-newstyle/build/x86_64-linux/ghc-9.6.7/CW3-0.1.0.0/doc/html/CW3/CW3.haddock

haddock-html:
    /home/lawal/Code_linux/Haskell/AAD-Project/CW3/dist-newstyle/build/x86_64-linux/ghc-9.6.7/CW3-0.1.0.0/doc/html/CW3
